[package]
name = "sdbootutil"
version = "0.1.0"
edition = "2021"
author = "Tobias GÃ¶rgens"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
